dat<-read.csv("fixBottle.csv",header=TRUE )
head(dat)
plot(c(dat$FirstFix, dat$LastFix),rep(log(dat$PopSize), 2), col=c("red", "blue"), xlab="Time to Fixation (generations)", ylab="ln(Population Size)")
lm1<-lm(log(PopSize)~FirstFix, data=dat)
summary(lm1)
lm2<-lm(log(PopSize)~LastFix, data=dat)
summary(lm2)
abline(lm1, col="red")
abline(lm2, col="blue")
legend("topright", legend=c("First Fix", "Last Fix"), col=c("red", "blue"), lty=rep(1), lwd=rep(1), pch=rep(21))
